import Joi from 'joi';
const image = Joi.string().uri({ scheme: ['https', 'http'] }).max(2000).allow('').default('');
export const meetingInput = Joi.object({ title: Joi.string().trim().max(200).required(), description: Joi.string().max(4000).allow('').default(''), location: Joi.string().trim().max(500).allow('').default(''), latitude: Joi.number().min(-90).max(90), longitude: Joi.number().min(-180).max(180), gpsRadiusMeters: Joi.number().integer().min(50).max(5000).default(200), coverImage: image, startsAt: Joi.date().iso().required(), reminderDays: Joi.number().integer().min(0).max(365).default(1), tiers: Joi.array().items(Joi.object({ count: Joi.number().integer().min(1).max(1000).required(), seconds: Joi.number().integer().min(1).max(3600).required() })).min(1).max(20).required(), fallbackSeconds: Joi.number().integer().min(1).max(3600).required() });
export const updateMeetingInput = Joi.object({ title: Joi.string().trim().max(200), description: Joi.string().max(4000).allow(''), location: Joi.string().trim().max(500).allow(''), latitude: Joi.number().min(-90).max(90).allow(null), longitude: Joi.number().min(-180).max(180).allow(null), gpsRadiusMeters: Joi.number().integer().min(50).max(5000), coverImage: image, startsAt: Joi.date().iso(), reminderDays: Joi.number().integer().min(0).max(365), tiers: Joi.array().items(Joi.object({ count: Joi.number().integer().min(1).max(1000).required(), seconds: Joi.number().integer().min(1).max(3600).required() })).min(1).max(20), fallbackSeconds: Joi.number().integer().min(1).max(3600) });
export const checkinInput = Joi.object({ userId: Joi.string().hex().length(24), name: Joi.string().trim().max(150), email: Joi.string().email().max(254).allow('').default(''), photoURL: image, coverImage: image });
export const controlInput = Joi.object({ action: Joi.string().valid('start', 'pause', 'resume', 'next', 'finish', 'cancel').required(), version: Joi.number().integer().min(0).required() });


export const qrMemberInput = Joi.object({ email: Joi.string().email().max(254).required(), password: Joi.string().min(1).max(200).required(), latitude: Joi.number().min(-90).max(90).required(), longitude: Joi.number().min(-180).max(180).required() });
export const qrGuestInput = Joi.object({ name: Joi.string().trim().min(2).max(150).required(), email: Joi.string().email().max(254).allow('').default(''), phone: Joi.string().trim().max(40).allow('').default(''), company: Joi.string().trim().max(150).allow('').default(''), latitude: Joi.number().min(-90).max(90).required(), longitude: Joi.number().min(-180).max(180).required() });
