version: '3.8'

services:
  igen-bni:
    image: ghcr.io/chung2310/bni-erp:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-igen-bni}
    restart: always
    ports:
      - "${PORT:-3012}:${PORT:-3012}"
    environment:
      PORT: ${PORT:-3012}
    env_file:
      - .env
    volumes:
      - .env:/app/.env
    networks:
      - default_network
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default_network:
    external: true
