// Shared light palette for the dashboard and meeting-control leaderboards.
export const MEMBER_RANKING_PODIUM = [
  {
    rankIndex: 3,
    rankNum: 4,
    heightClass: "h-28 sm:h-36",
    bgColor: "bg-sky-100",
    textColor: "text-sky-800",
    dividerColor: "border-sky-300/50",
    borderColor: "border-sky-200",
    badgeColor: "bg-sky-100 text-sky-800 font-semibold ring-2 ring-white shadow-2xs",
    ringColor: "ring-2 ring-sky-200",
    isTop1: false,
  },
  {
    rankIndex: 1,
    rankNum: 2,
    heightClass: "h-44 sm:h-52",
    bgColor: "bg-cyan-200",
    textColor: "text-cyan-800",
    dividerColor: "border-cyan-400/40",
    borderColor: "border-cyan-300",
    badgeColor: "bg-cyan-200 text-cyan-800 font-semibold ring-2 ring-white shadow-2xs",
    ringColor: "ring-2 ring-cyan-300",
    isTop1: false,
  },
  {
    rankIndex: 0,
    rankNum: 1,
    heightClass: "h-56 sm:h-64",
    bgColor: "bg-sky-300",
    textColor: "text-sky-800",
    dividerColor: "border-sky-500/30",
    borderColor: "border-sky-300 shadow-sm",
    badgeColor: "bg-sky-300 text-sky-800 font-semibold ring-2 ring-white shadow-2xs",
    ringColor: "ring-2 ring-sky-400",
    isTop1: true,
  },
  {
    rankIndex: 2,
    rankNum: 3,
    heightClass: "h-36 sm:h-44",
    bgColor: "bg-emerald-200",
    textColor: "text-emerald-800",
    dividerColor: "border-emerald-400/40",
    borderColor: "border-emerald-300",
    badgeColor: "bg-emerald-200 text-emerald-800 font-semibold ring-2 ring-white shadow-2xs",
    ringColor: "ring-2 ring-emerald-300",
    isTop1: false,
  },
  {
    rankIndex: 4,
    rankNum: 5,
    heightClass: "h-22 sm:h-28",
    bgColor: "bg-emerald-100",
    textColor: "text-emerald-800",
    dividerColor: "border-emerald-300/50",
    borderColor: "border-emerald-200",
    badgeColor: "bg-emerald-100 text-emerald-800 font-semibold ring-2 ring-white shadow-2xs",
    ringColor: "ring-2 ring-emerald-200",
    isTop1: false,
  },
];
